### ISSUE TITLE
Is this necessary? 

### ISSUE THREAD

**Issue by Andful** [KULeuven-MICAS/stream#37]
https://github.com/KULeuven-MICAS/stream/blob/6ac88776d1b9e5698f39014500f3d0ae7cde20a7/stream/classes/io/onnx/default.py#L21

Is this necessary? This breaks the CONCAT DNN operations, such as the one in SqueezeNet. Was it working before this change was introduces?

**Comment by asyms** [comment]
This is intended as the DummyNode should only exist for 'simple' operators where the dependencies can just be propagated. A concat operator requires more complex dependency propagation. This has since been changed. See:

- https://github.com/KULeuven-MICAS/stream/blob/master/stream/parser/onnx/concat.py
- https://github.com/KULeuven-MICAS/stream/blob/master/stream/workload/concat_node.py
